### ISSUE TITLE
Support ArrayFire CPU Backend for Linux

### ISSUE THREAD

**Issue by cryptodeal** [cryptodeal/zigTensor#4]
### What is the problem this feature would solve?

Enable use of `zigTensor` on Linux using the ArrayFire CPU backend; should only require modifying the `build.zig` setup to allow passing the bath to the executable/headers manually and then configure the `linkBackend` function to link the relevant files

### What is the feature you are proposing to solve the problem?

Support Linux ArrayFire CPU backend.

**Comment by cryptodeal** [comment]
Status: I've got all tests passing locally on Ubuntu Docker, but for some reason the tests exit with Exit Code 2 (in spite of listing 151/151 passing); debugging this and then will push latest code to close this issue.

**Comment by asilvas** [comment]
Great progress. Looking forward to trying your first release!

**Comment by cryptodeal** [comment]
Hmm, thought I had this sorted out as I was able to test/get this fixed locally using [nektos/act](https://github.com/nektos/act), which tests Github Actions via Docker, but it's still not passing in the Github Action hosted runner.

**Comment by cryptodeal** [comment]
Fixed with commit cec6fc596ca5ac321655e6b0108364359cefcaaf
